/*
 * Copyright 2018-2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.miku.r2dbc.mysql;

import io.r2dbc.spi.test.TestKit;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Base class considers integration tests of {@link TestKit}.
 */
abstract class MySqlTestKitSupport extends IntegrationTestSupport implements TestKit<String> {

    private final JdbcTemplate jdbcOperations;

    MySqlTestKitSupport(MySqlConnectionConfiguration configuration) {
        super(configuration);
        this.jdbcOperations = jdbc(configuration, null);
    }

    @Override
    public MySqlConnectionFactory getConnectionFactory() {
        return connectionFactory;
    }

    @Override
    public JdbcTemplate getJdbcOperations() {
        return jdbcOperations;
    }

    @Override
    public String getCreateTableWithAutogeneratedKey() {
        return "CREATE TABLE test (id INT PRIMARY KEY AUTO_INCREMENT, value INT)";
    }

    @Override
    public String getInsertIntoWithAutogeneratedKey() {
        return "INSERT INTO test VALUES (DEFAULT,100)";
    }

    @Override
    public String getIdentifier(int index) {
        return "v" + index;
    }

    @Override
    public String getPlaceholder(int index) {
        return "?v" + index;
    }

    @Override
    public String clobType() {
        return "TEXT";
    }
}
