name: Stage release to Maven Central

on:
  push:
    branches: [ release ]

jobs:
  build:
    if: github.repository == 'mirromutth/r2dbc-mysql'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Temurin 8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: Initialize Maven Version
        run: ./mvnw -q org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version
      - name: Set up GPG
        run: |
          mkdir -m 700 -p ~/.gnupg
          install -m 600 <(echo "${{ secrets.GPG_SECRING_ENCODED }}") ~/.gnupg/secring.gpg.b64
          install -m 600 <(base64 -d ~/.gnupg/secring.gpg.b64) ~/.gnupg/secring.gpg
          gpg -k
      - name: Release with Maven
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./ci/central.sh
      - name: Clean up GPG
        run: rm -rf ~/.gnupg
