name: MySQL 5.5

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Shutdown the Default MySQL
        run: sudo service mysql stop
      - name: Set up MySQL 5.5
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 5.5
          mysql database: r2dbc
          mysql root password: ${{ secrets.DatabasePassword }}
      - name: Integration test with MySQL 5.5
        run: mvn verify -B -Dgpg.skip=true -Dmaven.javadoc.skip=true -Dmaven.surefire.skip=true -Dtest.mysql.password=${{ secrets.DatabasePassword }} -Dtest.mysql.version=5.5 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
